-- Idempotent production repair for projects where the original CREATE TABLE
-- stopped with `relation "submissions" already exists`. It fills in the
-- current inbox shape without deleting or exposing any existing submission.

create table if not exists public.submissions (
  id bigint generated always as identity primary key,
  reference text not null unique,
  submission_type text not null,
  status text not null default 'received',
  source text not null default 'covenda-web',
  revision_of text,
  submitter_name text not null,
  submitter_email text not null,
  organization_name text,
  summary text not null,
  ready_count smallint,
  readiness_total smallint,
  details jsonb not null,
  readiness jsonb,
  consent boolean not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.submissions
  add column if not exists id bigint generated by default as identity,
  add column if not exists reference text,
  add column if not exists submission_type text,
  add column if not exists status text default 'received',
  add column if not exists source text default 'covenda-web',
  add column if not exists revision_of text,
  add column if not exists submitter_name text,
  add column if not exists submitter_email text,
  add column if not exists organization_name text,
  add column if not exists summary text,
  add column if not exists ready_count smallint,
  add column if not exists readiness_total smallint,
  add column if not exists details jsonb default '{}'::jsonb,
  add column if not exists readiness jsonb,
  add column if not exists consent boolean,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create unique index if not exists submissions_reference_unique_idx
  on public.submissions (reference)
  where reference is not null;

create index if not exists submissions_type_created_at_idx
  on public.submissions (submission_type, created_at desc);

create index if not exists submissions_status_created_at_idx
  on public.submissions (status, created_at desc);

create index if not exists submissions_revision_of_idx
  on public.submissions (revision_of)
  where revision_of is not null;

alter table public.submissions
  drop constraint if exists submissions_type_allowed,
  add constraint submissions_type_allowed
    check (submission_type in ('employer_intake', 'student_interest', 'call_request', 'university_partner')) not valid;

alter table public.submissions
  drop constraint if exists submissions_reference_format,
  add constraint submissions_reference_format
    check (reference ~ '^(EMP|STU|CALL|UNI)-[A-Z0-9]{6,20}$') not valid;

alter table public.submissions
  drop constraint if exists submissions_status_allowed,
  add constraint submissions_status_allowed
    check (status in ('received', 'reviewing', 'needs_information', 'packet_proposed', 'approval_pending', 'approved', 'declined', 'archived')) not valid;

alter table public.submissions
  drop constraint if exists submissions_source_allowed,
  add constraint submissions_source_allowed
    check (source = 'covenda-web') not valid;

alter table public.submissions
  drop constraint if exists submissions_readiness_pair,
  add constraint submissions_readiness_pair check (
    (ready_count is null and readiness_total is null)
    or (ready_count between 0 and readiness_total and readiness_total > 0)
  ) not valid;

alter table public.submissions
  drop constraint if exists submissions_consent_required,
  add constraint submissions_consent_required
    check (consent = true) not valid;

alter table public.submissions
  drop constraint if exists submissions_revision_reference_format,
  add constraint submissions_revision_reference_format
    check (revision_of is null or revision_of ~ '^EMP-[A-Z0-9]{6,20}$') not valid;

alter table public.submissions enable row level security;
alter table public.submissions force row level security;

revoke all on table public.submissions from public, anon, authenticated;
grant usage on schema public to service_role;
grant select, insert, update on table public.submissions to service_role;

do $$
declare
  identity_sequence text;
begin
  identity_sequence := pg_get_serial_sequence('public.submissions', 'id');
  if identity_sequence is not null then
    execute format('revoke all on sequence %s from public, anon, authenticated', identity_sequence);
    execute format('grant usage, select on sequence %s to service_role', identity_sequence);
  end if;
end $$;

comment on table public.submissions is
  'Private Covenda intake inbox. Browser roles have no access; server routes own ingestion.';

notify pgrst, 'reload schema';
